---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ci-log-based-dashboard-cluster
  version: "1.24"
  region: eu-central-1

managedNodeGroups:
- name: nodegroup-1
  instanceType: m5.large
  minSize: 1
  maxSize: 1
  desiredCapacity: 1